### ISSUE TITLE
Please update the crates.io version to 0.7.0

### ISSUE THREAD

**Issue by Zer0-** [ruma/ruma-events#11]
I cannot change ruma's dependency to ruma-events 0.7.0 because it won't pull it from crates.io. However ruma-events 0.6.0 does not build on my system (it relies on an older ruma-identifiers which doesn't compile)

**Comment by jimmycuadra** [comment]
Yikes, good catch! Sorry I forgot to publish to crates.io when I tagged 0.7.0. It's published now.
