### ISSUE TITLE
formatted body as part of "m.text"

### ISSUE THREAD

**Issue by jcgruenhage** [ruma/ruma-events#17]
It is currently not as easily possible to get the formatted body of a TextMessageEventContent as it is to get the non-formatted body. My guess would be that this is partly due to the lack of specification, as I couldn't find it.

**Comment by jcgruenhage** [comment]
[From #matrix-dev:matrix.org](https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1518366999724zlpbT:riot.ovh):
> There's talks of replacing msgtypes entirely
With a much more reusable construct

This means that it might not be worth implementing this, depending on if and when msgtypes are replaced.

**Comment by jimmycuadra** [comment]
Formatted body is a custom extension that's not in the spec right now. Take a look at this example event I just pulled from the Rust room:

``` json
{
  "origin_server_ts": 1526628443354,
  "sender": "@spivee:matrix.org",
  "event_id": "$15266284432212874VJJXB:matrix.org",
  "unsigned": {
    "age": 1693240
  },
  "content": {
    "body": "in theory `let x = &y;` is the same as `let ref x = y;`",
    "msgtype": "m.text",
    "formatted_body": "in theory <code>let x = &amp;y;</code> is the same as <code>let ref x = y;</code>",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!zXfJBqSUvXySmsZMtB:jki.re"
}
```
My hunch is that the Matrix team implemented this directly in Synapse to quickly support pretty messages in Riot. If/when it gets added to the spec, we'll support it too.
