### ISSUE TITLE
Make deserialization more robust

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-events#26]
It has happened multiple times for multiple people that a full sync response could not be deserialized with ruma-client because it either contained some ill-formed events or events that failed to parse because of a bug in ruma-events.

What should happen in those cases instead is those events being deserialized into some sort of `UnknownEvent` (of which there might be multiple variations, e.g. `UnknownRoomEvent` could also be a thing).

If somebody wants to work on this, I would recommend also joining [#ruma:matrix.org](https://matrix.to/#/#ruma:matrix.org) and discussion implementation strategies there before diving into the code.

**Comment by jimmycuadra** [comment]
This was resolved in [0.13.0](https://github.com/ruma/ruma-events/releases/tag/0.13.0).
