### ISSUE TITLE
Ensure we're using compatible numeric types

### ISSUE THREAD

**Issue by jimmycuadra** [ruma/ruma-events#27]
Florian brought this up in `#ruma:matrix:org`:

> While we are at breaking changes in ruma-events, I was recently made aware of this: https://matrix.org/docs/spec/appendices#canonical-json - all "integers" in the specification, e.g. powerlevels, can have the range `[-(2**53)+1, (2**53)-1]` unless noted to be positive only. From a quick check, it seems like ruma uses u64, i.e. `[0, (2**64)-1]`, while we should use i64 and reject `2**53 - 2**64` as invalid.
>
> Also, notes on integers to be positive only are much more sparse than I would have expected, might be an area where we have to go and fix the spec first instead of allowing negative integers everywhere.
>
> the `2**53` seemed especially odd, until I realized that this is the f64 float limit, and remembered that javascript has no real integers but represents everything as floats.
>
> at least for power level events, a power level of -1 is actually used regularily to mute people, so that would definitely be something that would break the current ruma. hopefully serde would just complain instead of having an integer underflow and giving the person MAX_INT powerlevel. ^^

**Comment by jplatte** [comment]
I built a crate for this kind of integer: https://crates.io/crates/js_int
It shouldn't be hard to migrate the relevant ids to `js_int::Int` (or sometimes `js_int::UInt`). Updating issue label.
