### ISSUE TITLE
`ruma_events::collections::all::RoomEvent` should implement `ruma_events::RoomEvent`

### ISSUE THREAD

**Issue by reivilibre** [ruma/ruma-events#28]
Title says it all, but a tiny bit more context can be found on [\[matrix\]](https://matrix.to/#/!wzHrsErnsyaqbpFiRQ:matrix.org/$15670608943383aRegR:librepush.net?via=matrix.org&via=privacytools.io&via=kde.org):

> If I have a ruma_events::collections::all::RoomEvent and I want to get the room_id or sender or something,
is there no better way than pattern matching every enum type to get it?
Am I missing something? I would expect the enum to implement ruma_events::RoomEvent; is there a problem with doing so?

> we haven't implemented that thus far, but that seems like a good idea
and the implementation of that would just be the giant match you'd currently have to do

**Comment by jplatte** [comment]
This will no longer be relevant with the 0.22 API refactoring.
