### ISSUE TITLE
sync events: "missing field `notifications`"

### ISSUE THREAD

**Issue by stoically** [ruma/ruma-events#39]
Hey, thanks for the excellent work on ruma and ruma-client!

I've tried with a fresh matrix.org account to join a new empty room created from riot and sent two hello world messages (from the example) to it. After that I performed a sync and one of the events results in 

`InvalidError:` "missing field `notifications`" (deserialization error)

serde json:
`
Object({"content": Object({"ban": Number(50), "events": Object({"m.room.avatar": Number(50), "m.room.canonical_alias": Number(50), "m.room.history_visibility": Number(100), "m.room.name": Number(50), "m.room.power_levels": Number(100)}), "events_default": Number(0), "invite": Number(0), "kick": Number(50), "redact": Number(50), "state_default": Number(50), "users": Object({"@gitpub:matrix.org": Number(100), "@riot-bot:matrix.org": Number(100)}), "users_default": Number(0)}), "event_id": String("$LlDm_U4AMOR6VszjvcO1AdWjaBQZyUpi2EBSc6P3sss"), "origin_server_ts": Number(1576487358648), "sender": String("@gitpub:matrix.org"), "state_key": String(""), "type": String("m.room.power_levels"), "unsigned": Object({"age": Number(17909137)})})
`

Not sure if that's expected behavior - if it is expected I'd be interested why that's the case. If you need code to reproduce please let me know.

**Comment by jplatte** [comment]
This is most likely a bug, potentially our `m.room.power_levels` event isn't up-to-date with the spec.

**Comment by jplatte** [comment]
Should be fixed by https://github.com/ruma/ruma-events/commit/dd16d0f2f082b16aa595d8d4c67ac63cdf47d547, do you need instructions on how to use git master with ruma-client?

**Comment by stoically** [comment]
Thanks for the quick turn-around! Since ruma-events is not in same workspace as ruma-client, I'd actually not know how to get ruma-client to use master, so if you have pointers how to do that, it'd be helpful for sure.

**Comment by jplatte** [comment]
You can [`[patch]`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section) the depency like so:

```toml
[patch.crates-io]
ruma-events = { git = "https://github.com/ruma/ruma-events" }
```

**Comment by jplatte** [comment]
@stoically Have you verified that this issue is fixed on master?

**Comment by stoically** [comment]
Just did, works fine now, thanks!

`RoomPowerLevels(PowerLevelsEvent { content: PowerLevelsEventContent { ban: 50, events: {RoomName: 50, RoomAvatar: 50, RoomCanonicalAlias: 50, RoomHistoryVisibility: 100, RoomPowerLevels: 100}, events_default: 0, invite: 0, kick: 50, redact: 50, state_default: 50, users: {UserId { hostname: Domain("matrix.org"), localpart: "riot-bot", port: 443, is_historical: false }: 100, UserId { hostname: Domain("matrix.org"), localpart: "gitpub", port: 443, is_historical: false }: 100}, users_default: 0, notifications: NotificationPowerLevels { room: 50 } }, event_id: EventId(UrlSafeBase64("LlDm_U4AMOR6VszjvcO1AdWjaBQZyUpi2EBSc6P3sss")), origin_server_ts: 1576487358648, prev_content: None, room_id: None, unsigned: Some(Object({"age": Number(209721794)})), sender: UserId { hostname: Domain("matrix.org"), localpart: "gitpub", port: 443, is_historical: false }, state_key: "" })`

**Comment by jplatte** [comment]
Nice! Going to close this, then.
