### ISSUE TITLE
Change room_id field in Room Events from Option<RoomId> to RoomId

### ISSUE THREAD

**Issue by aledomu** [ruma/ruma-events#43]
For some reason this field is not enforced, but every spec version of the protocol specifies that it is required.

**Comment by jimmycuadra** [comment]
It used to be required in ruma-events but it was changed to be optional a while back. I'm trying to remember why—I think it's because room event structs are sometimes embedded API requests/responses that don't always contain every field.

**Comment by jplatte** [comment]
This was the PR that made it optional: #20

**Comment by jplatte** [comment]
We could potentially provide stripped room events and make the regular room events require this field.

**Comment by emilazy** [comment]
related to #44?

**Comment by jplatte** [comment]
@emilazy kind of. But that issue is about events that are declared with `event!`, so should be non-room events based on that but contain a `room_id` field anyways. This issue is about `room_event!`s.

**Comment by jplatte** [comment]
When looking through the history of ruma-events, I found that early versions had `Event` as a generic type like `ToDevice` and `Stripped` now are. I think returning to that would easily solve the problem here by just having another of these generic types where the room ID is optional, with the main `RoomEvent` having a mandatory room_id field.

**Comment by aledomu** [comment]
Maybe that's just hair-splitting, but I see doing that as a potential source for mismatches between the content type and the event type (`Event`, `RoomEvent` or `StateEvent`). Having the traits implemented from the library doesn't have that kind of ambiguity problem. For the same reason I don't like that change regarding `Stripped`, but I ignore why it was deemed necessary.

**Comment by jplatte** [comment]
@aledomu We could still have the same traits for the content types, using them to limit the content types each of the generic event structs accepts as for the `content` field.

**Comment by jplatte** [comment]
This is done in the api22 branch.
