### ISSUE TITLE
Typing Event seems to be defined incorrectly

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-events#44]
It is not defined as a `room_event!`, but includes a `room_id` field, which is non-optional. However, `room_id`s are generally optional because they are omitted in `sync` responses (sync groups all events by room). Thus, we currently always fail to deserialize typing events from sync responses.

Reported on [#ruma:matrix.org](https://matrix.to/#/#ruma:matrix.org) by @timokoesters (thanks!)

**Comment by jplatte** [comment]
This also affects receipt events (reported in #46) and possibly others.

I don't yet know how to fix this because I previously assumed ephemeral and account-data events were non-room events, but then why do both receipt and typing events have a `room_id` field?

**Comment by emilazy** [comment]
It seems those events are explicitly scoped to rooms, per

* https://matrix.org/docs/spec/client_server/r0.6.0#id49
* https://matrix.org/docs/spec/client_server/r0.6.0#id58

**Comment by emilazy** [comment]
So I guess the correct thing to do here is to separate out the rest of the event structs from the `room_id`, and use the smaller type in the `/sync` response. I'm not sure what the best way to do this to match Ruma's existing conventions is – the simplest thing would be to copy-paste variants of the structs, but I'd personally be inclined to at least share the common fields between the two, and maybe even define a generic wrapper type to bundle a `room_id` with the rest of an event.

**Comment by jplatte** [comment]
> define a generic wrapper type to bundle a `room_id` with the rest of an event

I'd be in favor of something like that, but first want to look into why typing and receipt events are not `room_event!`s but still contain a `room_id`.

**Comment by emilazy** [comment]
The spec link I posted says:

> These are ephemeral events scoped to a `room_id`. This means they do not form part of the Event Graph but still have a `room_id` key.

which I think answers that? (But I'm not sure what `room_event!` is; `impl_room_event!` seems quite different.)

**Comment by jplatte** [comment]
Yeah sorry, didn't look at the link yet. That probably is the reason. The next question is then whether we want to keep the terminology of "room event" for events that are part of the event graph.

**Comment by emilazy** [comment]
The spec [seems to use the term that way](https://matrix.org/docs/spec/client_server/r0.6.0#types-of-room-events), so I think it'd be fine to keep, though I do agree that it's somewhat confusing.

**Comment by jplatte** [comment]
Fixed in 78eae67. We should still create separate types for the two variants of these events (with room_id, without room_id) but that can be tracked over at #43.
