### ISSUE TITLE
Impl ruma_events::collections::all::Event::from(ruma_events::collections::all::RoomEvent) etc.

### ISSUE THREAD

**Issue by valkum** [ruma/ruma-events#45]
Currently some methods returning a collection enum limit itself to a specific scope.

E.g. `IncomingTimeline` returns `ruma_events::collections::all::RoomEvent` but it would be nice if the events crate would implement a way to upcast `RoomEvent`s into `ruma_events::collections::all::Event` and the same for `StateEvent`

**Comment by jplatte** [comment]
Seems reasonable. So the traits to be implemented would be

* `impl From<StateEvent> for RoomEvent`
* `impl From<RoomEvent> for Event`
* `impl From<StateEvent> for Event` (implementation in terms of the other two)

right?

**Comment by valkum** [comment]
That what i thought of.

**Comment by jplatte** [comment]
Fixed in ac26770319ed7e1b4f649c8e1d245fd202d649be.
