### ISSUE TITLE
To-device events are missing a collection.

### ISSUE THREAD

**Issue by poljar** [ruma/ruma-events#50]
To-device messages are sent using the [sendToDevice](https://matrix.org/docs/spec/client_server/latest#put-matrix-client-r0-sendtodevice-eventtype-txnid) API endpoint. Those events will end up in a sync response in the `to_device` field.

An event that is contained in the to_device field of the sync response, as per [spec](https://matrix.org/docs/spec/client_server/latest#extensions-to-sync) will have the following fields:

* sender
* type
* content

Many of the events that are sent mainly as to-device events are implemented in ruma-events without the `sender` field. Examples for this are:

* [Dummy](https://github.com/ruma/ruma-events/blob/master/src/dummy.rs#L20)
* [RoomKeyRequest](https://github.com/ruma/ruma-events/blob/master/src/room_key_request.rs#L12)
* [RoomKey](https://github.com/ruma/ruma-events/blob/master/src/room_key.rs)
* [ForwardedRoomKey](https://github.com/ruma/ruma-events/blob/master/src/forwarded_room_key.rs#L11)
* I believe all of the [key verification events](https://github.com/ruma/ruma-events/blob/master/src/key/verification/accept.rs#L13)

Another a bit of a different case, the [EncryptedEvent](https://github.com/ruma/ruma-events/blob/master/src/room/encrypted.rs#L40), which corresponds to a `m.room.encrypted` event is implemented as a `RoomEvent` containing a `sender`, `event_id`, `origin_server_ts` among others but the spec states [this](https://matrix.org/docs/spec/client_server/latest#m-room-encrypted):

> This event type is used when sending encrypted events. It can be used either within a room (in which case it will have all of the Room Event fields), or as a to-device event.

Historically the `m.olm.v1.curve25519-aes-sha2` algorithm was sent as a room event but since the introduction of the `m.megolm.v1.aes-sha2` algorithm, `m.olm.v1` events are sent as to-device events while `m.megolm.v1` events are sent as room events.

Note that key verification events can end up as to-device as well as room events as well, a separate issue exists for this in #33.

**Comment by jplatte** [comment]
Fixed by #52.
