### ISSUE TITLE
Generate raw version of event / event content structs as part of `FromRaw` derive macro

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-events#67]
I didn't do this when splitting the `impl FromRaw` codegen into its own derive macro because it would have caused multiple `raw` modules inside the same defining scope to be generated with a naive implementation, which wouldn't work. However, I just had an idea to resolve this issue: We could have the `FromRaw` derive macro read an attribute on the struct that gives an alternative module name instead of `raw` if present. For example:

```rust
#[derive(FromRaw)]
#[from_raw(raw_mod = "raw_event")]
struct MyEvent { ... }

#[derive(FromRaw)]
#[from_raw(raw_mod = "raw_content")]
struct MyEventContent { ... }

// might or might not make sense
pub(crate) mod raw {
    pub use super::raw_event::*;
    pub use super::raw_content::*;
}
```

**Comment by DevinR528** [comment]
Can I work on this one, no one else is working on it?

**Comment by jplatte** [comment]
Nobody is working on it as far as I know, though I fear there's not going to be much left to do in GSoC if you continue working on the macro code until it starts.

**Comment by jplatte** [comment]
With the removal of the separate event structs as is being planned for 0.22, this could be implemented even without a separate `from_raw(raw_mod)` attribute :slightly_smiling_face:

**Comment by jplatte** [comment]
This has been implemented by @DevinR528 and merged on the api22 branch, will close now and re-open should there be problems with merging api22 into master.
