### ISSUE TITLE
API ideas for 0.22

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-events#82]
Here's my current thinking on how the API for ruma-events could change with the next release:

## Get rid of the traits `Event`, `RoomEvent` and `StateEvent`

Instead

* Add new generic structs like `ToDevice` and `Stripped`
  * `Event` with optional room, state fields
  * `NonRoomEvent` (possibly under a different name) with only the mandatory event fields
  * `RoomEvent` with optional state fields
  * `MessageEvent` with only the mandatory room fields
  * `StateEvent` with all fields mandatory
  * potentially others
* … which also means all the generated `Event` types will be dropped
  * because of this, there would no longer be a reason to have `Event` and `EventContent` suffixes. `FullyReadEventContent` can just become `FullyRead`. `EventJson<FullyReadEvent>` becomes `EventJson<Event<FullyRead>>`.
* … we could optionally gate which content types the generic structs (including those that already exist) accept using marker traits `EventContent`, `RoomEventContent` and `StateEventContent`

## Rename event enums

* `all::Event` => `AnyEvent`
* `all::RoomEvent` => `AnyRoomEvent`
* `all::StateEvent` => `AnyStateEvent`
* `only::Event` => `AnyNonRoomEvent`
* `only::RoomEvent` => `AnyMessageEvent`

with this new naming I think these should be exposed from the crate root rather than from a separate `collections` module.

## Expose all the types at the crate root

I'm less certain about this, but I could also imagine exposing all the event content types from the crate root. This would involve another renaming of many event content types, those that are scoped under a submodule like `room`. Examples:

* `fully_read::FullyReadEvent` => `Event<FullyRead>`
* `room::MessageEvent` => `Event<RoomMessage>`
* `room::message::feedback::FeedbackEventContent` => `RoomMessageFeedback`

CC @poljar who contributed some ideas w.r.t. renaming, @iinuwa and @aledomu who also expressed some opinions about potential ruma-events API changes in #ruma:matrix.org

**Comment by poljar** [comment]
Continuing from https://github.com/ruma/ruma-events/pull/78#issuecomment-623349693

> Well, maybe you're right. I've thought a bit about it and `RoomMessage` would fit in nicely with getting rid of the current traits and having more generic structs like `ToDevice` and `Stripped` for the top-level event structures.
> 
> Sorry for the confusion about `AnyRoomEvent`. The content collection we've been talking about would be called `AnyRoomEventContent`. Or do you consider the `Event` in that name unnecessary or redundant too?
> 

I don't mind the `Event` in there if it's a collection for the client receiving side (e.g. in the room timeline of a sync response). If this is meant for the sending side I think we'll want only one single collection so we can build stuff that gets sent using the to-device endpoint the same way we would build stuff that gets sent using the `room/{room_id}/send` endpoint.

**Comment by jplatte** [comment]
I don't know about sendToDevice, but `PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}` and `PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}` clearly shouldn't have the same collection type for their request bodies. If sendToDevice is also for message events like the send endpoint, then of course they should use the same type.

**Comment by jplatte** [comment]
To expand a bit on that, what I would roughly expect a client library to do if it wants to be a bit more ergonomic for the state / send / sendToDevice APIs is take `Into<ContentCollection>` as a parameter.

That would allow `.send(RoomMessage { ... })` as well as `.send(Encrypted { ... })`, `.set_state(RoomName { ... })`, `.set_state(RoomTopic { ... })`, but not `.send(RoomName { ... })` or `.set_state(RoomMessage { ... })`.

**Comment by dkasak** [comment]
Just as a side-note, an important client-side use case is to be able to send custom event types, so that's something to keep in mind.

**Comment by jplatte** [comment]
@dkasak Thanks for bringing that up. To support that, the event content collections can simply have a `Custom` variant like event collections already do.

**Comment by aledomu** [comment]
I consider the bit about marker traits really important. Other than that, nothing to disagree with.

**Comment by Dominaezzz** [comment]
I'm currently doing this generic `Event` type classes (struct in this case) pattern for represent any matrix event, instead of specific event types for each type.
The big issue I had was how to handle https://github.com/matrix-org/matrix-doc/issues/502 .

**Comment by jplatte** [comment]
What do you mean by "currently doing this"? Are you working on ruma-events / are you involved with an unrelated library and just wanted to share your experience / sth. else?

You're right that redaction events are a special case that has to be considered. There's also a few events that are not part of the room DAG but still have a `room_id` field at the event level (for example typing events).

**Comment by Dominaezzz** [comment]
Oh I forgot to say. I've got a thin [client sdk in Kotlin](https://github.com/Dominaezzz/matrix-kt) where I'm "currently doing this" and I wanted to share my experience and look for better ideas.

**Comment by jplatte** [comment]
@Dominaezzz So my current thinking is that there just have to be additional event structs (having recently gone through all events in the spec I know that `redacts` and `room_id` are the only special cases). So `RedactedEvent` would be its own, non-generic type while the events with a `room_id` field but no persistence in the DAG could have their own generic struct, probably named `EphemeralRoomEvent`.

What I'm not yet certain about is how to handle redaction events in event collections (`AnyRoomEvent`, `AnyMessageEvent`) and event content collections (`AnyRoomEventContent`, `AnyMessageEventContent`). It would seem like redactions can't be sent using the regular message sending endpoint despite being message events, so in a way it would make sense to have the content collections *not include* `RedactionEventContent`, but the event collections *include* redaction events. Maybe even sth. like:

```rust
type AnyRegularMessageEvent = MessageEvent<AnyMessageEventContent>;
enum AnyMessageEvent {
    Regular(AnyRegularMessageEvent),
    Redaction(RedactionEvent),
}
```

**Comment by Dominaezzz** [comment]
I'm not certain how this would be achieved in rust but I was thinking of [moving the redacts key](https://github.com/matrix-org/matrix-doc/pull/2174) during serialization.
This way we don't need a special redaction event type (since [MSC2174](https://github.com/matrix-org/synapse/issues/7486) will make it that way eventually).
I think this way is acceptable for clients, and servers implementing [MSC2174](https://github.com/matrix-org/matrix-doc/blob/master/proposals/2174-move-redacts-key.md) will probably do it this way.

I currently have this hierarchy. Some are a bit awkward to name, since they are one of a kind.
- `Event` (has type and content)
  - `RoomEvent` (has at least eventId)
    - `MessageEvent` (has no stateKey)
    - `StateEvent` (has stateKey)
  - `EphemeralEvent` (has a sender and/or `roomId`)
    - `ToDeviceEvent` (has no roomId)
    - (Not sure what to call this) (has roomId, stuff like `m.typing`)
    - (Not sure what to call this) (has sender, stuff like `m.presence`)
  - `AccountEvent` (has no extras except optional `roomId`)

Btw, what are event collections for? Why doesn't `Vec<AnyRegularMessageEvent>` suffice?

**Comment by jplatte** [comment]
I guess moving the redacts key during serialization would work, yeah. I'll have to think about it some more but I do like the idea.

> Btw, what are event collections for? Why doesn't `Vec<AnyRegularMessageEvent>` suffice?

Oh, "event collections" are the `AnyWhateverEvent` types. I guess the naming is a bit off, huh? I was planning to get rid of the `collections` module anyway and just renamed that section in the issue descripion to "event enums".

**Comment by jplatte** [comment]
I've thought about redaction events again and I think I will do it as explicitly as possible, leaving homeserver implementations the choice of sending current-format redaction events, new-format redaction events or current+new-compat redaction events (with duplicated `redacts` both in the event and content fields). I will make sure to provide convenience methods so clients don't have to care which format a redaction event is in.

**Comment by jplatte** [comment]
So basically something like

```rust
enum RedactionEvent {
    // assuming redaction events are valid in v1 rooms, otherwise change 1 to the appropriate number
    V1(RedactionV1Event),
    // assuming room version 7 includes the format change
    V7(RedactionV7Event),
    V1V7Compat(RedactionV1V7CompatEvent),
}

struct RedactionV1Event {
    // message event fields
    redacts: EventId,
    content: RedactionV1,
}

type RedactionV7Event = MessageEvent<RedactionV7>;

struct RedactionV1 { ... }
struct RedactionV7 { ... }

**Comment by jplatte** [comment]
> * `ToDeviceEvent` (has no roomId)

I've just checked this because I was very unclear about to-device events. This seems to not actually be true: `m.room.encrypted` can explicitly be used as a to-device event but required the `room_id` field to be meaningful ([spec](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-encrypted)).

Also, the to-device messaging [module specification](https://matrix.org/docs/spec/client_server/r0.6.1#id70) to me reads like *any* event can be sent using it (it doesn't even forbid state events, though that seems like something that should definitely be forbidden).

**Comment by poljar** [comment]
> I've just checked this because I was very unclear about to-device events. This seems to not actually be true: `m.room.encrypted` can explicitly be used as a to-device event but required the `room_id` field to be meaningful ([spec](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-encrypted)).

Huh? Where are you seeing a to-device event with a room id? If you mean the examples those are both room events.

> Also, the to-device messaging [module specification](https://matrix.org/docs/spec/client_server/r0.6.1#id70) to me reads like _any_ event can be sent using it (it doesn't even forbid state events, though that seems like something that should definitely be forbidden).

Yes, I think I already mentioned that, any type of event can be sent out. Clients need to check if the event makes sense for them. E.g. ignore m.room.member events that arrive as to-device events, check that a state event has a state key, otherwise it isn't a valid state event.

**Comment by jplatte** [comment]
Oh, so an `m.room.encrypted` event can contain a room event if sent as a room event itself, but not if sent as a to-device event? That makes sense I guess.

> Yes, I think I already mentioned that, any type of event can be sent out. Clients need to check if the event makes sense for them. E.g. ignore m.room.member events that arrive as to-device events, check that a state event has a state key, otherwise it isn't a valid state event.

If to-device events *never* have room fields though, state event checks are superfluous as the necessary fields can't possibly be present, no?

From what you're saying it sounds to me like generally to-device messaging can be used for non-room events only.

**Comment by poljar** [comment]
Perhaps I should say any type of content can be sent over the to-device endpoint. The server of course won't include the event id, room id if it's not a room event.

And yeah, the encrypted content can be anything and there's no way for the server to check. Per spec it should be content for some other unencrypted event type.

> If to-device events never have room fields though, state event checks are superfluous as the necessary fields can't possibly be present, no?

The necessary checks are superfluous in ruma since it won't de-serialize properly, that's correct, dynamically typed languages might need them.

> From what you're saying it sounds to me like generally to-device messaging can be used for non-room events only.

Depends on what we consider non-room events, the `m.room.encrypted` are sent as room events and as to-device events, all the `m.key.verification.*` events as well. The content will be the same, the top level fields will differ.

Another thing, some people wanted to use the to-device endpoint to send ephemeral messages between devices, that would likely be a `m.room.message` content sent as a to-device event. Considering the extensibility of Matrix we don't want to disallow people from sending such events as to-device events.

**Comment by jplatte** [comment]
My current thinking of the correct rules for events (this should really be explicit in the spec somewhere :roll_eyes:)

Generalizable:

* Everything has an `event_type` + `content` fields
* _Ephemeral room events_ have an additional `room_id` field
* _Room events_ have mandatory `event_id`, `origin_server_ts`, `room` and `sender` fields and an optional `unsigned` field
* _State events_ have all fields of stripped room events + `state_key` and an optional `prev_content`
* There are stripped versions of room events and state events that don't have a `room_id` field (used only in `/sync/ response)
* There is another even more stripped version of a state event that is used in the sync response for rooms a user has been invited to (has only the mandatory fields + `state_key` and `sender`)
* The term _message events_ is used for room events that are not state events
* Any non-room event can be send as a to-device event

Special rules:

* `m.presence` is the only non-room event with a mandatory `sender` field (other non-room events may have this field if sent using to-device messaging)
* `m.redacts` is the only event with a `redacts` field

**Comment by jplatte** [comment]
> Depends on what we consider non-room events, the `m.room.encrypted` are sent as room events and as to-device events, all the `m.key.verification.*` events as well. The content will be the same, the top level fields will differ.
> 
> Another thing, some people wanted to use the to-device endpoint to send ephemeral messages between devices, that would likely be a `m.room.message` content sent as a to-device event. Considering the extensibility of Matrix we don't want to disallow people from sending such events as to-device events.

Okay, so a to-device event (content) collection should consist of all events that are not state events, right? Since sending state events using to-device messaging would be pointless as the receiving side would have to discard the event anyway (and on the server side, there's also no point handling these differently to custom, non-specced to-device events).

**Comment by poljar** [comment]
> Okay, so a to-device event (content) collection should consist of all events that are not state events, right? Since sending state events using to-device messaging would be pointless as the receiving side would have to discard the event anyway (and on the server side, there's also no point handling these differently to custom, non-specced events).

Yeah I think so, and I agree, we don't need to support sending the ludicrous content types, that'll likely just confuse users and if someone really wants to send garbage (e.g. to test a server or something) they can do so using the custom mechanism.

**Comment by jplatte** [comment]
> the `m.room.encrypted` are sent as room events and as to-device events, all the `m.key.verification.*` events as well

The bit about `m.key.verification.*` sometimes being sent as room events is nowhere to be found in the spec and it's not obvious from their names either. Are you positive about this? Do we need another spec issue? 😞

**Comment by poljar** [comment]
It's here https://github.com/matrix-org/matrix-doc/pull/2241.

**Comment by jplatte** [comment]
Opened #117 to track the remaining work for this, and #118 specifically for MSC2174 which was discussed briefly above.

@Dominaezzz What we ended up implementing is not documented very well yet, but will be once we release ruma-events 0.22. You are also welcome to join [#ruma:matrix.org](https://matrix.to/#/#ruma:matrix.org) and discuss this kind of stuff there! :)
