### ISSUE TITLE
Add alt_aliases to CanonicalAliasEventContent

### ISSUE THREAD

**Issue by timokoesters** [ruma/ruma-events#98]
https://github.com/matrix-org/matrix-doc/pull/2432/files#diff-a9ccbaea3cb53ab4c6147d0a7e7f10c2R61

**Comment by jplatte** [comment]
So adding this wouldn't be complicated. But it's still not released yet and also right now adding any fields is a breaking change. I think we should probably transition to (generated) builders for every event content struct + making them `#[non_exhaustive]`. I guess we could start a branch with these not-yet-released spec things though.
